### ISSUE TITLE
Звук печати продолжается после выхода в меню

### ISSUE THREAD

**Issue by Regnaris** [Regnaris/TODR-visualnovel#1]
При запуске игры, когда идет отображение вступительного текста (цитата на латыни), которая сопровождается звуком печати, и если выйти в главное меню в этот момент, то звук продолжится.

**Comment by CrewGTW** [comment]
Что с этим можно сделать?

**Comment by Regnaris** [comment]
Вроде исправил, нужно проверить.

**Comment by Regnaris** [comment]
Исправлено.
